
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      #MYSQL_USER: root
      MYSQL_PASSWORD: abner
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
